version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    image: craigrmccown/kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_CREATE_TOPICS: "renderurls:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
